### ISSUE TITLE
Enable SSL on website

### ISSUE THREAD

**Issue by swatarianess** [Project-Skill-Tree/Skill-Tree-Website#5]
It would be nice to secure the website, it is just part of habing good operational security. 

The website is hosted via github pages, and only a single button needs to be pressed in order to enable SSL support. However, the custom domain is not configured correctly 😔

Steps to configure ssl support can be found [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors).

**Comment by Gamsti1337** [comment]
This should help:

https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https
